site_name: Thumby Color

nav:
  - Home: home.md
  - Getting Started With Thonny: pages/getting-started-with-thonny/getting-started-with-thonny.md
  - First Game: pages/first-game/first-game.md
  - Documentation and Examples: pages/documentation-and-examples/documentation-and-examples.md
  - FAQ: FAQ.md
  - About/Contact: About.md

copyright: Copyright &copy; 2024 TinyCircuits

# code highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

# all the colors of light/dark mode
theme:
  logo: images/Thumby_Logo_Wte.png
  favicon: images/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      # primary:
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      # primary:
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top # 'Back to top' button when scrolling up a page
  name: material
  custom_dir: docs/color
  # icon repo for 'GitHub' repo - but it's actually the Thumby Code Editor
  icon:
    repo: octicons/link-external-16

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# This sheet just has color changes
extra_css:
  - stylesheets/extra.css

# Use the github repo feature to link to the Thumby Code Editor
repo_url: https://code.thumby.us/
repo_name: Thumby Code Editor

# social footer icons and links
extra:
  analytics:
    provider: google
    property: UA-118275183-3
  homepage: https://thumby.us
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TinyCircuits
      name: TinyCircuits on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/nkwR3WBBXD
      name: TinyCircuits on Discord
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TinyCircuits
      name: TinyCircuits on Twitter
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/tinycircuits/
      name: TinyCircuits on Instagram
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/TinyCircuits/
      name: TinyCircuits on Facebook
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCc4SQjmFcgsbvQFuYNgHuVg
      name: TinyCircuits on YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/tinycircuits-com/
      name: TinyCircuits on LinkedIn
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@tinycircuits
      name: TinyCircuits on TikTok
